### ISSUE TITLE
Recipe search - handle response

### ISSUE THREAD

**Issue by willmowlam** [jennysiu/nutriSmartApp#22]
2. Handle JSON responses and parse relevant data (recipe names, ingredients, instructions, plus anything else feels is relevant and can include).

**Comment by willmowlam** [comment]
Recipe instructions aren't available in returned data.

In the recipe results/view we can have a button to "Get instructions/method" that opens the source recipe webpage in a new window - we can name the window so that only one is used for each recipe viewed. I considered trying to retrieve website content in a modal or iframe but these may not always work due to website/browser security restrictions.

Also perhaps show a bootstrap icon on the button to show its opening in a new window so the user expects this behaviour.

**Comment by jennysiu** [comment]
yes sounds good. Would it make sense to open up a new HTML page for this? This is always an option (easy option) and can be done in the fastest time probably!

**Comment by willmowlam** [comment]
Absolutely. And done.
